version: '3.8'
services:
    owl-api:
        container_name: owl-rest
        build:
            context: ./rest
        ports:
            - "4000:4000"
        volumes:
            - ./rest:/app
        environment: 
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_HOST: "${POSTGRES_HOST}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DATABASE: "${POSTGRES_DATABASE}"
            POSTGRES_PORT: "${POSTGRES_PORT}"
        depends_on: 
            - db
        links:
            - db
    owl-graphql:
        container_name: owl-graphql
        build:
            context: ./graphql
        ports:
            - "4001:4001"
        volumes:
            - ./graphql:/app
        depends_on: 
            - owl-api
        links:
            - owl-api
    owl-update:
        container_name: owl-update
        build:
            context: ./dbUpdate
        volumes:
            - ./dbUpdate:/code
        environment: 
            DB_USER: "${POSTGRES_USER}"
            DB_HOST: "${POSTGRES_HOST}"
            DB_PASS: "${POSTGRES_PASSWORD}"
            DB_NAME: "${POSTGRES_DATABASE}"
            DB_PORT: "${POSTGRES_PORT}"
        depends_on: 
            - db
        links:
            - db
        stdin_open: true
        tty: true
    db:
        container_name: owl-pg
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        ports:
            - "8001:5432"
        volumes: 
            - pgdata:/var/lib/postgresql/data
    pgadmin:
        container_name: owl-pgadmin4
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
            PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
        ports:
            - "5050:80"
        depends_on: 
            - db
        links: 
            - db
        logging: 
            driver: none
volumes: 
    pgdata: